name: CPU & Memory Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cpuload-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run CPU & memory load tester
        # Adjust this to match your actual script name and arguments
        run: |
          echo "Starting CPU & memory load test"
          python cpuload-python.py --gb 2 --seconds 60 --cpu 75 --cpu_duration 60

      - name: Confirm test completion
        run: |
          echo "✔️ Load test finished without errors"
